FROM postgres:alpine

# The default user is "postgres"
ENV POSTGRES_PASSWORD test123

# Saying this WILL create the DB
ENV POSTGRES_DB demo_postgres_db

# Don't actually need to include the script to
# create a DB if you use POSTGRES_DB
# COPY init.sql /docker-entrypoint-initdb.d/

