FROM postgres:alpine

ENV POSTGRES_PASSWORD test123  # The default user is "postgres"
ENV POSTGRES_DB demo_postgres_db  # Saying this will NOT create the DB!

# Include the script that will create the DB we'll be connecting to!
COPY init.sql /docker-entrypoint-initdb.d/

